const Articles = [
    {
        writer: "Nicolas Cole",
        title: "20 Things Most People Learn Too Late In Life",
        subtitle: "Life is a journey of twists and turns, peaks and valleys, mountains to climb and oceans to explore.",
        date: "Oct 17",
        time: "5 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*xF11-TSkpJSCgLc75f-DFw.jpeg",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*BO36vszZiTsOZl0EU6lwLA.jpeg",
    },
    {
        writer: "Alan Trapulionis",
        title: "How 7 Lines of Code Turned Into a $36 Billion Empire",
        subtitle: "Two Irish brothers in their 20s outplayed the finance industry with seven lines of code",
        date: "Aug 26",
        time: "4 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*ZpqTjur1EEzN4KzM4e-Bnw.png",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*g8_4A8UOYl6zIwvhAx1YJg.jpeg",
    },
    {
        writer: "Gillian May",
        title: "The First Signs of Alcoholic Liver Damage Are Not in the Liver",
        subtitle: "Not enough alcoholics are educated about this",
        date: "Sep 30",
        time: "6 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*GhG8ZeoE0TGfCHwL9SCrfw.png",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*Nr83WxHTus-khshg5p8DDQ.png",
    },
    {
        writer: "Heiki Kohal",
        title: "What Does a Healthy and Compatible Relationship Look Like?",
        subtitle: "If you have that, it should be safe to walk down the aisle.",
        date: "Oct 29",
        time: "4 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*bQrOCsmXteRwFJQ7plGXHQ.jpeg",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*DCF8YSGUjv3m5VMshtvzdA.jpeg",
    },
    {
        writer: "Sinem Günel",
        title: "7 Things You Should Never Do in the Morning",
        subtitle: "And what to do instead.",
        date: "Oct 30",
        time: "8 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*8OIW1rabg1zNia0RjTm0KQ.png",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*oJmYlYfST1OVWXQefqu-lw.jpeg",
    },
    {
        writer: "Sofien Kaabar",
        title: "A New Modified Version of the Bollinger Bands in Python",
        subtitle: "Creating an Alternative Volatility Bands System",
        date: "Nov 7",
        time: "5 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*NZI8Qh3vwxOLZj4N_zurFg@2x.png",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*0l7-vV_6zXMjAZzpRLM2xw.jpeg",
    },
    {
        writer: "Kaki Okumura",
        title: "How Japanese People Stay Fit for Life, Without Ever Visiting a Gym",
        subtitle: "For people stressed or intimidated by fitness culture",
        date: "Nov 6",
        time: "4 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*HQTxFkIf5fymNTatLc0qjA.jpeg",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*oj6N_VogT8cdkUk58sSLHg.jpeg",
    },
    {
        writer: "Joana Carneiro",
        title: "My Software Engineer Roadmap",
        subtitle: "Intro",
        date: "Nov 22",
        time: "7 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*Xd2uZaVHfrGOP14W_3UQRg.jpeg",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*t1dU-ilItNvLVkMddbvHpw.png",
    },
    {
        writer: "Glenna Gill",
        title: "What About Men Who Don’t Cheat?",
        subtitle: "There is a difference between a loser and a keeper.",
        date: "Nov 12",
        time: "4 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*2jAEzux2mwkkBwftv7evGA.png",
        pictureurl: "https://miro.medium.com/fit/c/250/166/0*qXX-1Cj4MXoRKoaZ",
    },
    {    
        writer: "Renata Gomes",
        title: "Marriage Disproportionally Benefits Men",
        subtitle: "And women are quitting it in droves.",
        date: "Nov 13",
        time: "6 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*1GYfCE9tsEE2LnypaTM4fg.png",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*mbHXb_A-vpLDXL7M7R7zTg.jpeg",
    },
    {
        writer: "Alexander M. Combstrong",
        title: "To Become Happier, Ask Yourself These Two Questions Every Night",
        subtitle: "The one-minute exercise can make a profound difference",
        date: "Oct 14",
        time: "3 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*uWbn_ZpGom5xlrE-bX-EuQ.jpeg",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*tAXQcg0_ZG0jTnrSe5aLrA.jpeg",
    },
    {
        writer: "Business Insider",
        title: "This is what it looks like when things fall apart",
        subtitle: "Rudy Giuliani’s pathetic press conference underscored how little President Trump has to back his claims of election fraud.",
        date: "Nov 21",
        time: "5 min",
        profileurl: "https://miro.medium.com/fit/c/25/25/1*PW6sWfilAMqxRZRBpj572Q.png",
        pictureurl: "https://miro.medium.com/fit/c/250/166/1*64qHxWPsfibMBlP-BbA9RQ.jpeg",
    },
]

export default Articles